# Generated by Django 4.2.4 on 2023-08-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='activate',
            new_name='active',
        ),
    ]
